/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * aiba-central-backend
 * AIBA 중앙서버 백엔드입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface TokensResponseDto {
  /** 액세스 토큰 */
  accessToken: string;
  /** 리프레시 토큰 */
  refreshToken: string;
}
