/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * aiba-central-backend
 * AIBA 중앙서버 백엔드입니다.
 * OpenAPI spec version: 0.0.1
 */
import { faker } from "@faker-js/faker";
import { rest } from "msw";

export const getAuthControllerLoginMock = () => ({
  accessToken: faker.word.sample(),
  refreshToken: faker.word.sample(),
});

export const getAuthControllerRefreshMock = () => ({
  accessToken: faker.word.sample(),
  refreshToken: faker.word.sample(),
});

export const getAuthControllerLogoutMock = () => faker.random.word();

export const getAuthMSW = () => [
  rest.post("*/auth/login", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getAuthControllerLoginMock()),
    );
  }),
  rest.post("*/auth/refresh", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getAuthControllerRefreshMock()),
    );
  }),
  rest.post("*/auth/logout", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getAuthControllerLogoutMock()),
    );
  }),
];
