/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * aiba-central-backend
 * AIBA 중앙서버 백엔드입니다.
 * OpenAPI spec version: 0.0.1
 */
import { rest } from "msw";

export const getDefaultMSW = () => [
  rest.get("*/ping", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
];
